BUNDLES = [
    '//apps/restconf/api:onos-apps-restconf-api',
    '//apps/restconf/common:onos-apps-restconf-common',
    '//apps/restconf/restconfmgr:onos-apps-restconf-restconfmgr',
    '//apps/restconf/ymsadapter:onos-apps-restconf-ymsadapter',
    '//apps/restconf/rpp:onos-apps-restconf-rpp',
]

onos_app (
  title = 'RESTCONF Service Module',
  category = 'Utility',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
)
